# Generated by Django 5.1.4 on 2025-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.BigIntegerField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("university", models.CharField(blank=True, max_length=100, null=True)),
                ("course", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEBSITE", "Website"),
                            ("LINKEDIN", "LinkedIn"),
                            ("INSTAGRAM", "Instagram"),
                        ],
                        default="WEBSITE",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lead_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DROP_NOT_INTERESTED", "Drop - Not Interested"),
                            ("BLANK", "Blank"),
                            ("BUSY", "Busy"),
                            ("SWITCH_OFF", "Switch Off"),
                            ("PROSPECT", "Prospect"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
            },
        ),
    ]
