# Generated by Django 4.2.21 on 2025-08-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_enquiry_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="enquiry",
            name="course",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="lead_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Website", "Website"),
                    ("LinkedIn", "LinkedIn"),
                    ("Instagram", "Instagram"),
                ],
                default="Website",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="lead_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DROP NOT INTERESTED", "DROP NOT INTERESTED"),
                    ("BLANK", "BLANK"),
                    ("BUSY", "BUSY"),
                    ("SWITCH OFF", "SWITCH OFF"),
                    ("PROSPECT", "PROSPECT"),
                ],
                default="BLANK",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="university",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
