# Generated by Django 5.2.4 on 2025-08-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('Website', 'Website'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram')], default='Website', max_length=100, null=True)),
                ('lead_stage', models.CharField(blank=True, choices=[('DROP NOT INTERESTED', 'DROP NOT INTERESTED'), ('BLANK', 'BLANK'), ('BUSY', 'BUSY'), ('SWITCH OFF', 'SWITCH OFF'), ('PROSPECT', 'PROSPECT')], default='BLANK', max_length=100, null=True)),
            ],
        ),
    ]
