# Generated by Django 5.2.4 on 2025-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by_teacher', models.BooleanField(default=False, help_text='Checked = teacher has reached out')),
            ],
        ),
    ]
