# Generated by Django 5.2.4 on 2025-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEdu', '0002_leadsource_leadstage_alter_enquiry_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='consulted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
