# Generated by Django 5.2.4 on 2025-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("mobile_no", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("course", models.CharField(max_length=100)),
            ],
        ),
    ]
